CREATE DATABASE employee;
USE employee;
CREATE TABLE emp_record_table (
    EMP_ID       VARCHAR(10) PRIMARY KEY,
    FIRST_NAME   VARCHAR(50),
    LAST_NAME    VARCHAR(50),
    GENDER       CHAR(1),
    ROLE         VARCHAR(100),
    DEPT         VARCHAR(50),
    EXP          INT,
    COUNTRY      VARCHAR(50),
    CONTINENT    VARCHAR(50),
    SALARY       INT,
    EMP_RATING   INT,
    MANAGER_ID   VARCHAR(10),
    PROJ_ID      VARCHAR(10)
);
CREATE TABLE proj_table (
    PROJECT_ID   VARCHAR(10) PRIMARY KEY,
    PROJ_NAME    VARCHAR(100),
    DOMAIN       VARCHAR(50),
    START_DATE   DATE,
    CLOSURE_DATE DATE,
    DEV_QTR      VARCHAR(10),
    STATUS       VARCHAR(20)
);
CREATE TABLE data_science_team (
    EMP_ID      VARCHAR(10) PRIMARY KEY,
    FIRST_NAME  VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    GENDER      CHAR(1),
    ROLE        VARCHAR(100),
    DEPT        VARCHAR(50),
    EXP         INT,
    COUNTRY     VARCHAR(50),
    CONTINENT   VARCHAR(50)
);
SELECT * FROM emp_record_table;
SELECT * FROM proj_table;
SELECT e.EMP_ID, e.FIRST_NAME, e.LAST_NAME, p.PROJ_NAME, p.STATUS
FROM emp_record_table e
LEFT JOIN proj_table p
ON e.PROJ_ID = p.PROJECT_ID;
SELECT DEPT, COUNT(*) AS total_employees
FROM emp_record_table
GROUP BY DEPT;
SELECT DEPT, FIRST_NAME, LAST_NAME, SALARY
FROM emp_record_table
WHERE (DEPT, SALARY) IN (
    SELECT DEPT, MAX(SALARY)
    FROM emp_record_table
    GROUP BY DEPT
);
SELECT EMP_ID, FIRST_NAME, LAST_NAME
FROM emp_record_table
WHERE PROJ_ID IS NULL;
SELECT CONTINENT, AVG(SALARY) AS avg_salary
FROM emp_record_table
GROUP BY CONTINENT;
SELECT STATUS, COUNT(*) AS total_projects
FROM proj_table
GROUP BY STATUS;
SELECT d.EMP_ID, d.FIRST_NAME, d.ROLE, e.PROJ_ID
FROM data_science_team d
LEFT JOIN emp_record_table e
ON d.EMP_ID = e.EMP_ID;

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT
FROM emp_record_table;
SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING
FROM emp_record_table
WHERE EMP_RATING < 2;
SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING
FROM emp_record_table
WHERE EMP_RATING > 4;
SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING
FROM emp_record_table
WHERE EMP_RATING BETWEEN 2 AND 4;
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME
FROM emp_record_table
WHERE DEPT = 'FINANCE';
SELECT MANAGER_ID, COUNT(*) AS REPORTER_COUNT
FROM emp_record_table
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;
SELECT * FROM emp_record_table WHERE DEPT = 'HEALTHCARE'
UNION
SELECT * FROM emp_record_table WHERE DEPT = 'FINANCE';
SELECT DEPT, EMP_ID, FIRST_NAME, LAST_NAME, ROLE, EMP_RATING,
       (SELECT MAX(EMP_RATING) 
        FROM emp_record_table e2 
        WHERE e2.DEPT = e1.DEPT) AS MAX_RATING
FROM emp_record_table e1
ORDER BY DEPT;
SELECT ROLE, MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY
FROM emp_record_table
GROUP BY ROLE;
SELECT EMP_ID, FIRST_NAME, LAST_NAME, EXP,
       RANK() OVER (ORDER BY EXP DESC) AS EXP_RANK
FROM emp_record_table;
CREATE OR REPLACE VIEW high_salary_employees AS
SELECT EMP_ID, FIRST_NAME, LAST_NAME, COUNTRY, SALARY
FROM emp_record_table
WHERE SALARY > 6000;
SELECT * FROM high_salary_employees;
SELECT *
FROM emp_record_table
WHERE EXP > (SELECT AVG(EXP) FROM emp_record_table);
DELIMITER //
CREATE PROCEDURE exp_more_than_3()
BEGIN
    SELECT * FROM emp_record_table WHERE EXP > 3;
END //
DELIMITER ;
CALL exp_more_than_3();
DELIMITER //
CREATE FUNCTION check_role(exp INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
    IF exp <= 2 THEN RETURN 'JUNIOR DATA SCIENTIST';
    ELSEIF exp <= 5 THEN RETURN 'ASSOCIATE DATA SCIENTIST';
    ELSEIF exp <= 10 THEN RETURN 'SENIOR DATA SCIENTIST';
    ELSEIF exp <= 12 THEN RETURN 'LEAD DATA SCIENTIST';
    ELSE RETURN 'MANAGER';
    END IF;
END //
DELIMITER ;
SELECT EMP_ID, FIRST_NAME, ROLE, EXP, check_role(EXP) AS STANDARD_ROLE
FROM data_science_team;
CREATE INDEX idx_firstname ON emp_record_table(FIRST_NAME);
SELECT EMP_ID, FIRST_NAME, SALARY, EMP_RATING,
       (0.05 * SALARY * EMP_RATING) AS BONUS
FROM emp_record_table;
SELECT CONTINENT, COUNTRY, AVG(SALARY) AS AVG_SALARY
FROM emp_record_table
GROUP BY CONTINENT, COUNTRY;

























 